export const optionTags: any = [
    'Array',
    'String',
    'Hash Table',
    'Linked List',
    'Math',
    'Two Pointers',
    'Binary Search',
    'Divide and Conquer',
    'Dynamic Programming',
    'Backtracking',
    'Stack',
    'Heap',
    'Greedy',
    'Sort',
    'Bit Manipulation',
    'Tree',
    'Depth-first Search',
    'Breadth-first Search',
    'Union Find',
    'Graph',
    'Design',
    'Topological Sort',
    'Trie',
    'Binary Indexed Tree',
    'Segment Tree',
    'Binary Search Tree',
    'Recursion',
    'Brainteaser',
    'Memoization',
    'Queue',
    'Minimax',
    'Reservoir Sampling',
    'Ordered Map',
    'Geometry',
    'Random',
    'Rejection Sampling',
    'Sliding Window',
    'Line Sweep',
    'Rolling Hash',
    'Suffix Array',
    'Geometry',
    'Random',
    'Rejection Sampling',
    'Sliding Window',
    'Line Sweep',
    'Rolling Hash',
    'Suffix Array',
    'Geometry',
    'Random',
    'Rejection Sampling',
    'Sliding Window',
    'Line Sweep',
    'Rolling Hash',
    'Suffix Array',
    'Geometry',
    'Random',
    'Rejection Sampling',
    'Sliding Window',
    'Line Sweep',
    'Rolling Hash',
    'Suffix Array',
    'Geometry',
    'Random',
    'Rejection Sampling',
    'Sliding Window',
    'Line Sweep',
    'Rolling Hash',
    'Suffix Array',
    'Geometry',
    'Random',
    'Rejection Sampling',
    'Sliding Window',
    'Line Sweep',
    'Rolling Hash',
    'Suffix Array',
    'Geometry',
    'Random',
    'Rejection Sampling',
    'Sliding Window',
    'Line Sweep',
    'Rolling Hash',
    'Suffix Array',
]